import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/app/component";
import { SearchProvider } from "@/app/context/SearchContext";
import { NavigationProvider } from "./context/NavigationContext";
import { CarouselContainer } from "./context/CarouselContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SearchProvider>
        <NavigationProvider>
          <body className={inter.className}>
            <Navbar />
            <main className="main">{children}</main>
            <Footer />
          </body>
        </NavigationProvider>
      </SearchProvider>
    </html>
  );
}
